#    Copyright (c) Perpetual Intelligence L.L.C. All Rights Reserved.
#
#    For license, terms, and data policies, go to:
#    https://terms.perpetualintelligence.com

name: build-test-push

concurrency: github-release

# Manual trigger for deployment
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      suffix:
        type: choice
        description: 'The package deployment suffix'
        required: true
        options:
        - preview
        - rc
        - release
        default: preview
      registry:
        type: choice
        description: 'The package registry'
        required: true
        options:
        - github
        - nuget        
        default: github
        
jobs:
  setup:    
    runs-on: ubuntu-latest
    environment: github-release
    timeout-minutes: 10
    
    # Define environment variables to authenticate the package feeds
    env:
      PI_GITHUB_USERNAME_ENV: ${{ secrets.PI_GITHUB_USERNAME }}
      PI_GITHUB_PAT_ENV: ${{ secrets.PI_GITHUB_PAT }}
      PI_NUGET_PAT_ENV: ${{ secrets.PI_NUGET_API_KEY }}
      PI_PUBLISH_REGISTRY: github
      PI_CI_REFERENCE: package
      PI_CLI_TEST_ONLINE_LIC: ${{ secrets.PI_GITHUB_CLI_TEST_ONLINE_LIC }}
      PI_CLI_TEST_OFFLINE_LIC: ${{ secrets.PI_GITHUB_CLI_TEST_OFFLINE_LIC }}
      
    steps:

    # Checktout
    - name: Checkout
      uses: actions/checkout@v3

    # Print directory
    - name: Print
      if: ${{ false }}  # Debug
      run: ls -R
      shell: bash

    # Read env    
    - name: Read Env
      run: cat .github/package_version.env >> $GITHUB_ENV                
      continue-on-error: false
      
    # Protocols package version
    # E.g. 2.3.8-preview.221225369 (latest build version including preview)
    # PI_DEPENDENCIES_SUFFIX will be empty for release version
    - name: Dependencies
      run: |
        echo "PI_PROTOCOLS_PACKAGE_VERSION=${{ env.PI_MAJOR_VERSION }}.${{ env.PI_MINOR_VERSION }}.${{ env.PI_PATCH_VERSION }}${{ env.PI_DEPENDENCIES_SUFFIX }}" >> $GITHUB_ENV
      continue-on-error: false
    
    # Build Number
    # Establish a unique build number for current run DMYY{RUN_NUMBER}{RUN_ATTEMPT} e.g. 11223234
    # Ignore leading 0 in day and month.
    # https://stackoverflow.com/questions/54066437/date-month-in-bash-without-leading-0-or-space
    - name: Build Number
      run: echo "PI_BUILD_NUMBER=$(date +'%-d%-m%y')${{ github.run_number }}${{ github.run_attempt }}" >> $GITHUB_ENV
      continue-on-error: false
    
    # Setup preview package versions based on trigger
    # Format: <package>.2.3.6-preview.2201032602
    - name: Default metadata (rc)
      if: ${{ github.event.inputs.suffix == '' }}
      run: echo "PI_CI_PACKAGE_VERSION=${{ env.PI_MAJOR_VERSION }}.${{ env.PI_MINOR_VERSION }}.${{ env.PI_PATCH_VERSION }}-rc.${{ env.PI_BUILD_NUMBER }}" >> $GITHUB_ENV
      continue-on-error: false
    
    # Setup preview package versions
    # Format: <package>.2.3.6-preview.2201032602
    - name: Preview metadata
      if: ${{ github.event.inputs.suffix == 'preview' }}
      run: echo "PI_CI_PACKAGE_VERSION=${{ env.PI_MAJOR_VERSION }}.${{ env.PI_MINOR_VERSION }}.${{ env.PI_PATCH_VERSION }}-preview.${{ env.PI_BUILD_NUMBER }}" >> $GITHUB_ENV
      continue-on-error: false
      
    # Setup rc package versions
    # Format: <package>.2.3.6-rc.2201032602
    - name: RC metadata
      if: ${{ github.event.inputs.suffix == 'rc' }}
      run: echo "PI_CI_PACKAGE_VERSION=${{ env.PI_MAJOR_VERSION }}.${{ env.PI_MINOR_VERSION }}.${{ env.PI_PATCH_VERSION }}-rc.${{ env.PI_BUILD_NUMBER }}" >> $GITHUB_ENV
      continue-on-error: false
      
    # Setup release package versions
    # Format: <package>.2.3.6
    - name: Release metadata
      if: ${{ github.event.inputs.suffix == 'release' }}
      run: echo "PI_CI_PACKAGE_VERSION=${{ env.PI_MAJOR_VERSION }}.${{ env.PI_MINOR_VERSION }}.${{ env.PI_PATCH_VERSION }}" >> $GITHUB_ENV
      continue-on-error: false

    # Setup publish registry (github or nuget)
    # PI_PUBLISH_REGISTRY defaults to github
    - name: Registry metadata
      if: ${{ github.event.inputs.registry != '' }}
      run: echo "PI_PUBLISH_REGISTRY=${{ github.event.inputs.registry }}" >> $GITHUB_ENV
      continue-on-error: false
    
    # Print all env and directory
    - name: Print
      if: ${{ false }}
      run: |
        env
        ls -R
      shell: bash
    
    # Setup .Net with global.json
    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    # Restore
    - name: Restore
      run: dotnet restore --verbosity minimal

    # Build
    - name: Build
      run: dotnet build -c Release --no-restore --verbosity minimal
      
    # Test
    - name: Test
      run: dotnet test --no-build --verbosity minimal

    # Pack
    - name: Pack
      run: dotnet pack -p:PackageVersion=${{ env.PI_CI_PACKAGE_VERSION }} --no-build -c Release -o _packages -v minimal
      
    # GITHUB
    - name: Github Push
      if: ${{ env.PI_PUBLISH_REGISTRY == 'github' }}
      run: dotnet nuget push --skip-duplicate --no-symbols --api-key ${{ env.PI_GITHUB_PAT_ENV }} --source github

    # NUGET - 1
    # First push to github (for package cadence, Nuget requires package verification)
    - name: Github Push
      if: ${{ env.PI_PUBLISH_REGISTRY == 'nuget' }}
      run: dotnet nuget push --skip-duplicate --no-symbols --api-key ${{ env.PI_GITHUB_PAT_ENV }} --source github
      
    # NUGET - 2
    # Second push to Nuget (for package cadence, Github will be used and in production Nuget after package verification)
    - name: Nuget Push
      if: ${{ env.PI_PUBLISH_REGISTRY == 'nuget' }}
      run: dotnet nuget push --skip-duplicate --no-symbols --api-key ${{ env.PI_NUGET_PAT_ENV }} --source nuget.org
